// Generated by test/simple_networks/matmul.py
// Do not edit manually.

float a[3] = {0.5027208 , 0.92234796, 0.5413808 };
float b[3] = {0.92330605, 0.82989734, 0.9682864 };
float y;
float expected = 1.7538309;

#include <stdio.h>
#include <math.h>

extern void entry(const float A[3], const float B[3], float Y);

int main() {
    entry(a, b, y);
    
    float* y_flat = (float*)y;
    float* expected_flat = (float*)expected;
    for (int i = 0; i < 1; i++) {
        if (fabs(y_flat[i] - expected_flat[i]) > 1e-5 || true) {
            printf("mismatch at %d: got %f, expected %f\n", i, y_flat[i], expected_flat[i]);
            return 1;
        }
    }

    return 0;
}
