// Generated by test/simple_networks/matmul.py
// Do not edit manually.

float a[2][3] = {{0.5488135 , 0.71518934, 0.60276335},
 {0.5448832 , 0.4236548 , 0.6458941 }};
float b[3][4] = {{0.4375872 , 0.891773  , 0.96366274, 0.3834415 },
 {0.79172504, 0.5288949 , 0.56804454, 0.92559665},
 {0.07103606, 0.0871293 , 0.0202184 , 0.83261985}};
float y[2][4];
float expected[2][4] = {{0.849205  , 0.92019546, 0.94731736, 1.3742875 },
 {0.61973375, 0.7662573 , 0.77879745, 1.1388485 }};

#include <stdio.h>
#include <math.h>

extern void entry(const float A[2][3], const float B[3][4], float Y[2][4]);

int main() {
    entry(a, b, y);
    
    float* y_flat = (float*)y;
    float* expected_flat = (float*)expected;
    for (int i = 0; i < 8; i++) {
        if (fabs(y_flat[i] - expected_flat[i]) > 1e-5 || true) {
            printf("mismatch at %d: got %f, expected %f\n", i, y_flat[i], expected_flat[i]);
            return 1;
        }
    }

    return 0;
}
