// Generated by test/simple_networks/matmul.py
// Do not edit manually.

float a[3] = {0.1598453 , 0.04680635, 0.97073144};
float b[3][4] = {{0.00386035, 0.17857997, 0.61286676, 0.0813696 },
 {0.8818965 , 0.71962017, 0.96638995, 0.50763553},
 {0.30040368, 0.5495006 , 0.93081874, 0.52076143}};
float y[4];
float expected[4] = {0.33350673, 0.5956454 , 1.046772  , 0.54228663};

#include <stdio.h>
#include <math.h>

extern void entry(const float A[3], const float B[3][4], float Y[4]);

int main() {
    entry(a, b, y);
    
    float* y_flat = (float*)y;
    float* expected_flat = (float*)expected;
    for (int i = 0; i < 4; i++) {
        if (fabs(y_flat[i] - expected_flat[i]) > 1e-5 || true) {
            printf("mismatch at %d: got %f, expected %f\n", i, y_flat[i], expected_flat[i]);
            return 1;
        }
    }

    return 0;
}
