// Generated by test/simple_networks/matmul.py
// Do not edit manually.

float a[2][3][4] = {{{0.03961552, 0.0599443 , 0.06107854, 0.90773296},
  {0.7398839 , 0.89806235, 0.6725823 , 0.5289399 },
  {0.30444637, 0.99796224, 0.36218905, 0.47064894}},

 {{0.37824517, 0.97952694, 0.17465839, 0.327988  },
  {0.6803487 , 0.06320762, 0.6072494 , 0.4776465 },
  {0.28399998, 0.23841327, 0.5145127 , 0.36792758}}};
float b[4] = {0.4565199 , 0.3374774 , 0.9704937 , 0.13343944};
float y[2][3];
float expected[2][3] = {{0.21871883, 1.3641658 , 0.8900808 },
 {0.716516  , 0.9849924 , 0.75853807}};

#include <stdio.h>
#include <math.h>

extern void entry(const float A[2][3][4], const float B[4], float Y[2][3]);

int main() {
    entry(a, b, y);
    
    float* y_flat = (float*)y;
    float* expected_flat = (float*)expected;
    for (int i = 0; i < 6; i++) {
        if (fabs(y_flat[i] - expected_flat[i]) > 1e-5 || true) {
            printf("mismatch at %d: got %f, expected %f\n", i, y_flat[i], expected_flat[i]);
            return 1;
        }
    }

    return 0;
}
