// Generated by test/simple_networks/matmul.py
// Do not edit manually.

float a[3][4] = {{0.9197828 , 0.03603382, 0.17477201, 0.38913468},
 {0.9521427 , 0.30002892, 0.16046764, 0.8863047 },
 {0.4463944 , 0.9078756 , 0.16023047, 0.6611175 }};
float b[4] = {0.44026375, 0.07648677, 0.69646317, 0.24739875};
float y[3];
float expected[3] = {0.6256969, 0.7731726, 0.541126 };

#include <stdio.h>
#include <math.h>

extern void entry(const float A[3][4], const float B[4], float Y[3]);

int main() {
    entry(a, b, y);
    
    float* y_flat = (float*)y;
    float* expected_flat = (float*)expected;
    for (int i = 0; i < 3; i++) {
        if (fabs(y_flat[i] - expected_flat[i]) > 1e-5 || 1) {
            printf("mismatch at %d: got %f, expected %f\n", i, y_flat[i], expected_flat[i]);
            return 1;
        }
    }

    return 0;
}
